name:                puck-core
version:             0.1.0.0
github:              "drsooch/puck-core"
license:             BSD3
author:              "Nick Suchecki"
maintainer:          "nicksuchecki@gmail.com"
copyright:           "None"

extra-source-files:
- README.md
- ChangeLog.md

description:         Please see the README on GitHub at <https://github.com/drsooch/puck-core#readme>

dependencies:
- base >= 4.7 && < 5
- optparse-applicative
- async
- postgresql-simple
- hslogger
- aeson
- text
- bytestring
- containers
- generic-lens

default-extensions:
#- DataKinds
- RecordWildCards
- DeriveGeneric
- DuplicateRecordFields
- FlexibleContexts
#- MultiParamTypeClasses
- OverloadedLabels
- OverloadedStrings
#- TypeApplications
- AllowAmbiguousTypes
#- RankNTypes

library:
  source-dirs: src

tests:
  puck-core-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - puck-core
